name: call_marriage_score_recorder
description: A score tracking app for Call Marriage (Call Break) game.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
